<?php

namespace ReclamationBundle\Repository;

/**
 * Appel_d_offreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Appel_d_offreRepository extends \Doctrine\ORM\EntityRepository
{
}
