<?php

namespace ReclamationBundle\Repository;

/**
 * Prop_App_offreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Prop_App_offreRepository extends \Doctrine\ORM\EntityRepository
{
}
