resources_homepage:
    path:     /
    defaults: { _controller: ResourcesBundle:Default:index }
afficherFleet:
    path:     /afficherFleet
    defaults: { _controller: ResourcesBundle:Fleet:afficherTableFleet }
fleet_supp:
    path:     /supprimerFleet/{matriculation}
    defaults: { _controller: ResourcesBundle:Fleet:supprimer }
fleet_modif:
    path:     /modifierFleet/{matriculation}
    defaults: { _controller: ResourcesBundle:Fleet:ModifierFleet }
ajouterFleet:
    path:     /ajouterFleet
    defaults: { _controller: ResourcesBundle:Fleet:ajouterFleet }
afficherMagazin:
    path:     /afficherMagazin
    defaults: { _controller: ResourcesBundle:Magazin:afficherTableMagazin }
magazin_supp:
    path:     /supprimerMagazin/{id_mag}
    defaults: { _controller: ResourcesBundle:Magazin:supprimer }
ajouterMagazin:
    path:     /ajouterMagazin
    defaults: { _controller: ResourcesBundle:Magazin:ajouterMagazin }
magazin_modif:
    path:     /modifierMagazin/{id_mag}
    defaults: { _controller: ResourcesBundle:Magazin:ModifierMagazin }
aaaa:
    path:     /call
    defaults: { _controller: ResourcesBundle:Magazin:call }

rechercherMagazin:
    path:     /rechercherMagazin
    defaults: { _controller: ResourcesBundle:Magazin:search }

rechercherFleet:
    path:     /rechercherFleet
    defaults: { _controller: ResourcesBundle:Fleet:search }
magazin_affecter:
    path:     /affecterMagazin/{id_mag}
    defaults: { _controller: ResourcesBundle:Magazin:affecterMagazin }
ajoutMagazinier:
    path:     /ajoutMagazinier/{id_mag}
    defaults: { _controller: ResourcesBundle:Magazin:ajouterMagazinier }
articleAffecter:
    path:     /affecterArticle/{idArticle}
    defaults: { _controller: ResourcesBundle:Magazin:affecterArticle }
article_affecter:
    path:     /articleAffecter/{idArticle}
    defaults: { _controller: ResourcesBundle:Magazin:ajouterArticle }
