<?php

namespace FluxBundle\Repository;

/**
 * FluxTransactionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxTransactionsRepository extends \Doctrine\ORM\EntityRepository
{

}
