reclamation_index:
    path:     /show
    defaults: { _controller: "ReclamationBundle:Reclamation:showReclamation" }



reclamation_create:
    path:     /createReclamation
    defaults: { _controller: "ReclamationBundle:Reclamation:create" }

