user_redirect:
    path:     /user-redirect
    defaults: { _controller: AuthBundle:UserRedirect:userRedirect }

redirect_to_login:
    path:   /
    defaults: { _controller: AuthBundle:UserRedirect:redirectToLogin }
