flux:
    resource: "@FluxBundle/Resources/config/routing.yml"
    prefix:   /

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix:   /

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /article

app:
    resource: '@AppBundle/Controller/'
    type: annotation
