
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

resources:
    resource: "@ResourcesBundle/Resources/config/routing.yml"
    prefix:   /resources


dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

livraison:
    resource: "@LivraisonBundle/Resources/config/routing.yml"
    prefix:   /livraison
flux:
    resource: "@FluxBundle/Resources/config/routing.yml"
    prefix:   /flux

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix:   /

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /article

app:
    resource: '@AppBundle/Controller/'
    type: annotation
