auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix:   /auth

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
