<?php

namespace LivraisonBundle\Repository;

/**
 * BonDeLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonDeLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
