<?php

namespace LivraisonBundle\Repository;

/**
 * LivraisonCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
