<?php

namespace ResourcesBundle\Repository;

/**
 * MagazinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazinRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLocation($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM ResourcesBundle:Magazin p
                WHERE p.location LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
