<?php

namespace ResourcesBundle\Repository;

/**
 * MagazinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazinRepository extends \Doctrine\ORM\EntityRepository
{
}
