<?php

namespace ResourcesBundle\Repository;

/**
 * MagazinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazinRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMagazins($str,$str2){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m
                FROM ResourcesBundle:Magazin m
                WHERE m.location = :str and m.category = :str2 '
            )
            ->setParameter('str', $str)->setParameter('str2',$str2)
            ->getResult();
    }
    public function findMagazin($category,$capacity){
        return $this->getEntityManager()
            ->createQuery(
                'select m
                From ResourcesBundle:Magazin m
                where (m.capacity - m.capacityRest) >= :str '
            )->setParameter('str',$capacity)->getResult();
    }
}
