flux_homepage:
    path:     /
    defaults: { _controller: FluxBundle:Default:index }


ajouter_facture:
    path:     /ajouter_factures
    defaults: { _controller:FluxBundle:Facture:ajouter }


afficher_transactions:
    path:     /afficher_transactions
    defaults: { _controller:FluxBundle:FluxTransaction:afficherTransaction }