
ajouter_facture:
    path:     /ajouter_factures
    defaults: { _controller:FluxBundle:Facture:ajouter }


afficherfacture:
    path:     /afficher_facture
    defaults: { _controller:FluxBundle:FluxTransaction:facture }


flux_home:
    path:     /
    defaults: { _controller:FluxBundle:FluxTransaction:fluxHome }

generer_facture:
    path:     /facture/{id}
    defaults: { _controller:FluxBundle:FluxTransaction:genererFacture }


liste_transaction_by_date:
<<<<<<< HEAD
    path:     /transactions/{date}
    defaults: { _controller:FluxBundle:FluxTransaction:getTransactionByDate }

generer_excel:
    path:     /transaction.xlsx
    defaults: { _controller: FluxBundle:FluxTransaction:generateExcelFile, _format: xlsx }
=======
    path:     /transactions
    defaults: { _controller:FluxBundle:FluxTransaction:getTransactionByDate }

liste_transaction_by_nature:
    path:     /transactions/{nature}
    defaults: { _controller:FluxBundle:FluxTransaction:getTransactionByNature }

statistiques:
    path:     /stats
    defaults: { _controller:FluxBundle:FluxTransaction:statistiques }

generer_excel:
    path:     /transaction.xlsx
    defaults: { _controller: FluxBundle:FluxTransaction:generateExcelFile, _format: xlsx }

search_liste_transaction:
    path:     /search
    defaults: { _controller:FluxBundle:FluxTransaction:search }
>>>>>>> master

search_liste_transaction2:
    path:     /search2
    defaults: { _controller:FluxBundle:FluxTransaction:search2 }


