
ajouter_facture:
    path:     /ajouter_factures
    defaults: { _controller:FluxBundle:Facture:ajouter }


afficherfacture:
    path:     /afficher_facture
    defaults: { _controller:FluxBundle:FluxTransaction:facture }


flux_home:
    path:     /
    defaults: { _controller:FluxBundle:FluxTransaction:fluxHome }
