<?php

namespace ArticleBundle\Repository;
use Doctrine\ORM\EntityRepository;
use ArticleBundle\Entity\Article;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
<<<<<<< HEAD
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM ArticleBundle:Article p
                WHERE p.name LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
=======
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.idArticle IN (:array)')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
>>>>>>> master
    }
}
