<?php

namespace ArticleBundle\Repository;
use Doctrine\ORM\EntityRepository;
use ArticleBundle\Entity\Category;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;
/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM ArticleBundle:Category p
                WHERE p.label LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
