livraison_homepage:
    path:     /
    defaults: { _controller: LivraisonBundle:Default:index }

liste_livraison:
    path:     /liste-livraison
    defaults: { _controller: LivraisonBundle:Livraison:listeLivraison }

ajouter_livraison:
    path: /ajouter-livraison
    defaults: { _controller: LivraisonBundle:Livraison:ajouterLivraison }

view_single_livraison:
    path: /view-livraison/{id}
    defaults: { _controller: LivraisonBundle:Livraison:viewSingleLivraison }

update_single_livraison:
    path: /update-livraison/{id}
    defaults: { _controller: LivraisonBundle:Livraison:updateSingleLivraison }

view_livraison_by_status:
    path: /liste-livraison/{status}
    defaults: { _controller: LivraisonBundle:Livraison:viewLivraisonByStatus }

view_livraison_by_livreur:
    path: /liste-livraison/livreur/{id}
    defaults: { _controller: LivraisonBundle:Livraison:getLivraisonByLivreur }

search_livraison:
    path: /liste-livraison-search/
    defaults: { _controller: LivraisonBundle:Livraison:searchMultiCriteria }
