supprimer:
    path:  /supprimer/{id}
    defaults: { _controller: CommandeBundle:Panier:supprimer }

ajouter:
    path:  /ajouter/{id}
    defaults: { _controller: CommandeBundle:Panier:ajouter }

panier:
    path:  /panier
    defaults: { _controller: CommandeBundle:Panier:panier }
validation:
    path:  /validation
    defaults: { _controller: CommandeBundle:Validation:validation }

