<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5fxjxyt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5fxjxyt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5fxjxyt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5fxjxyt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5fxjxyt\appDevDebugProjectContainer([
    'container.build_hash' => '5fxjxyt',
    'container.build_id' => 'e3158889',
    'container.build_time' => 1580513506,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5fxjxyt');
