<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSphdqi3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSphdqi3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSphdqi3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSphdqi3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSphdqi3\appDevDebugProjectContainer([
    'container.build_hash' => 'Sphdqi3',
    'container.build_id' => '07ce2b08',
    'container.build_time' => 1580977599,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSphdqi3');
