reclamation_reclamation:
    resource: "@ReclamationBundle/Resources/config/routing/reclamation.yml"
    prefix:   /reclamation

reclamation_homepage:
    path:     /
    defaults: { _controller: ReclamationBundle:Default:index }

reclamation_show:
        path:     /show
        defaults: { _controller: "ReclamationBundle:Reclamation:showReclamation" }

reclamation_create:
    path:     /createReclamation
    defaults: { _controller: "ReclamationBundle:Reclamation:createReclamation" }

reclamation_edit:
    path:     /status/{id}
    defaults: { _controller: "ReclamationBundle:Reclamation:edit" }

reclamation_recherche:
    path:     /status/{choix}
    defaults: { _controller: "ReclamationBundle:Reclamation:recherche" }













appel_d_offre_index:
    path:     /
    defaults: { _controller: "ReclamationBundle:Appel_d_offre:index" }

appel_d_offre_show:
    path:     /{id}/show
    defaults: { _controller: "ReclamationBundle:Appel_d_offre:show" }

appel_d_offre_all:
    path: /showTender
    defaults: {_controller: "ReclamationBundle:Appel_d_offre:showTenders"}

appel_d_offre_new:
    path:     /new
    defaults: { _controller: "ReclamationBundle:Appel_d_offre:createTenders" }

appel_d_offre_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReclamationBundle:Appel_d_offre:edit" }

appel_d_offre_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReclamationBundle:Appel_d_offre:delete" }

articleTender_add:
    path: /{id}/addArticleTender
    defaults: {_controller: "ReclamationBundle:Appel_d_offre:addArticle"}
article_add:
    path: /{id}/{idArticle}/addArticleTender
    defaults: {_controller: "ReclamationBundle:Appel_d_offre:addArticle2"}

articleTender_price:
    path: /{id}/price
    defaults: {_controller: "ReclamationBundle:Appel_d_offre:addPrice"}